# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install .NET Aspire workload
      run: dotnet workload install aspire

    - name: Set Build Variables
      id: dateStep
      run: |
        export sha7=${SHA7::7}
        export buildVersion=$(date '0.0.0-beta${{ github.run_number }}')
      
        echo "::set-output name=buildVersion::$buildVersion"
        echo "::set-output name=buildMode::$buildMode"
        echo "::set-output name=bumpBranch::$bumpBranch"
        echo "::set-output name=sha7::$sha7"
        echo "::set-output name=buildChangeSet::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | grep .yml$)"


    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack nugets
      run: dotnet pack -c Release /p:Version=${{ steps.dateStep.outputs.buildVersion }} -p ReleaseNotes="${{github.event.release.body}}" --output .
